name = "d1_connector"
main = "worker.js"
compatibility_date = "2024-08-01"
workers_dev = true

[vars]
AUTH_USERNAME = "root"         # Or use `wrangler secret`
AUTH_PASSWORD = "rootPasword"

[[d1_databases]]
binding = "DB_name"
database_name = "name"
database_id = "<your-database-id>"

[[d1_databases]]
binding = "DB_name2"
database_name = "name2"
database_id = "<your-database-id>"
